logging:
  level:
    root: info

server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/employee
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jms:
    pub-sub-domain: true

activemq:
  broker-url: tcp://localhost:61616


emp:
  jms:
    topic: EmpTopic
